In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (1.6.17)
Requirement already satisfied: six>=1.10 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (4.66.5)
Requirement already satisfied: python-slugify in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (2.2.2)
Requirement already satisfied: bleach in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from requests->kaggle) (3.8)
Requirement already satisfied: colorama in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [3]:
import kaggle

In [4]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [5]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip') 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [6]:
#read data from the file and handle null values
import pandas as pd
df = pd.read_csv('orders.csv', na_values=['Not Available','unknown'])
unique_values = {col: df[col].head(20).unique() for col in df.columns}
unique_values

{'Order Id': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 'Order Date': array(['2023-03-01', '2023-08-15', '2023-01-10', '2022-06-18',
        '2022-07-13', '2022-03-13', '2022-12-28', '2022-01-25',
        '2023-03-23', '2023-05-16', '2023-03-31', '2023-12-25',
        '2022-02-11', '2023-07-18', '2023-11-09', '2022-02-04',
        '2023-08-04', '2022-01-23', '2022-01-11'], dtype=object),
 'Ship Mode': array(['Second Class', 'Standard Class', nan], dtype=object),
 'Segment': array(['Consumer', 'Corporate', 'Home Office'], dtype=object),
 'Country': array(['United States'], dtype=object),
 'City': array(['Henderson', 'Los Angeles', 'Fort Lauderdale', 'Concord',
        'Seattle', 'Fort Worth', 'Madison', 'West Jordan', 'San Francisco'],
       dtype=object),
 'State': array(['Kentucky', 'California', 'Florida', 'North Carolina',
        'Washington', 'Texas', 'Wisconsin', 'Utah'], dtype=object),
 'Postal Code': array([42420, 90036, 33311, 90032, 28027, 98103, 76106, 53711, 84084,
        94109]),
 'Region': array(['South', 'West', 'Central'], dtype=object),
 'Category': array(['Furniture', 'Office Supplies', 'Technology'], dtype=object),
 'Sub Category': array(['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage',
        'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper'],
       dtype=object),
 'Product Id': array(['FUR-BO-10001798', 'FUR-CH-10000454', 'OFF-LA-10000240',
        'FUR-TA-10000577', 'OFF-ST-10000760', 'FUR-FU-10001487',
        'OFF-AR-10002833', 'TEC-PH-10002275', 'OFF-BI-10003910',
        'OFF-AP-10002892', 'FUR-TA-10001539', 'TEC-PH-10002033',
        'OFF-PA-10002365', 'OFF-BI-10003656', 'OFF-AP-10002311',
        'OFF-BI-10000756', 'OFF-ST-10004186', 'OFF-ST-10000107',
        'OFF-AR-10003056', 'TEC-PH-10001949'], dtype=object),
 'cost price': array([ 240,  600,   10,  780,   20,   50,  860,   90, 1470,  750,  360,
          60,    0,  610,  170]),
 'List Price': array([ 260,  730,   10,  960,   20,   50,  910,  110, 1710,  410,   70,
           0,  670,   60,  210]),
 'Quantity': array([2, 3, 5, 7, 4, 6, 9]),
 'Discount Percent': array([2, 3, 5, 4])}

In [7]:
#rename columns names ..make them lower case and replace space with underscore
df.rename(columns={'Order Id':'order_id', 'City':'city'})
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [8]:
#derive new columns discount , sale price and profit
df['discount']=df['list_price']*df['discount_percent']*.01
df['sale_price']= df['list_price']-df['discount']
df['profit']=df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [9]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [10]:
#convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [11]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [12]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [13]:
#drop cost price list price and discount percent columns
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

In [14]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [15]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [31]:
from sqlalchemy import create_engine
!pip install psycopg2-binary
engine = create_engine(f"postgresql+psycopg2://postgres:Souvik@localhost:5432/Datasd")
connection = engine.connect()

Requirement already satisfied: psycopg2-binary in c:\users\souvik\appdata\local\programs\python\python312\lib\site-packages (2.9.9)

In [32]:
engine = create_engine(f"postgresql+psycopg2://postgres:Souvik@localhost:5432/Datasd")
connection = engine.connect()

In [27]:
# Establish a connection
conn = engine.connect()

In [33]:
#load the data into sql server using append option
# Write DataFrame to SQL Table
df.to_sql('df_orders', con=engine, index=False, if_exists='append')

994